# Serverless.yml configuration snippet for createApplication function
# Add this to the functions section of your serverless.yml

functions:
  # Create Application - Submit application for a listing
  createApplication:
    handler: src/features/rentals/createApplication.handler
    timeout: 30
    events:
      - http:
          path: /listings/{listingId}/applications
          method: post
          cors: true
          authorizer:
            name: CognitoUserPoolAuthorizer
            type: COGNITO_USER_POOLS
            arn: 
              Fn::GetAtt:
                - CognitoUserPool
                - Arn

# Required environment variables (already configured in main serverless.yml):
# LISTINGS_TABLE: Baliciaga-Listings-${sls:stage}
# APPLICATIONS_TABLE: Baliciaga-Applications-${sls:stage}

# Required IAM permissions (already configured in main serverless.yml):
# - dynamodb:GetItem, PutItem, Query permissions for Listings and Applications tables
# - Cognito User Pool authorization

# Required dependencies in package.json:
# - uuid: for generating unique applicationId values 