# Serverless configuration for getApplications function
# Add this to the functions section in serverless.yml

  # Get Applications for Listing (Owner Only)
  getApplications:
    handler: src/features/rentals/getApplications.handler
    timeout: 30
    events:
      - http:
          path: /listings/{listingId}/applications
          method: get
          cors: true
          authorizer:
            name: CognitoUserPoolAuthorizer
            type: COGNITO_USER_POOLS
            arn: 
              Fn::GetAtt:
                - CognitoUserPool
                - Arn 